# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UaULCLTAgdKs5Vwsvu9xTfvyrTDfhVcN
"""

import random

# Predefined words
words = ["python", "computer", "programming", "developer", "algorithm"]

# Select a random word
word = random.choice(words)

guessed_letters = []
wrong_guesses = 0
max_wrong_guesses = 6

print("=" * 40)
print("        🎮 HANGMAN GAME")
print("=" * 40)
print("Guess the word one letter at a time!")
print(f"You have {max_wrong_guesses} incorrect guesses.\n")

while wrong_guesses < max_wrong_guesses:

    # Display current word
    display_word = ""

    for letter in word:
        if letter in guessed_letters:
            display_word += letter + " "
        else:
            display_word += "_ "

    print("Word:", display_word)
    print("Guessed letters:", " ".join(guessed_letters))
    print(f"Wrong guesses: {wrong_guesses}/{max_wrong_guesses}")
    # Check if player has won
    if all(letter in guessed_letters for letter in word):
        print("\n🎉 Congratulations! You guessed the word!")
        print("The word was:", word)
        break

    guess = input("\nEnter a letter: ").lower().strip()

    # Validate input
    if len(guess) != 1 or not guess.isalpha():
        print("❌ Please enter one valid letter.")
        continue

    # Check duplicate guess
    if guess in guessed_letters:
        print("⚠️ You already guessed that letter.")
        continue

    guessed_letters.append(guess)

    # Check guess
    if guess in word:
        print("✅ Correct guess!")
    else:
        wrong_guesses += 1
        print("❌ Incorrect guess!")

else:
    print("\n💀 Game Over!")
    print("The correct word was:", word)

print("\nThank you for playing! 🎮")