# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_1rDOGoboyNSv5_jKfDP3xlf7Ru1k2YW
"""

def chatbot_response(user_input):
    """
    Returns a response based on the user's message.
    """

    user_input = user_input.lower().strip()

    if user_input in ["hello", "hi", "hey"]:
        return "Hi! 👋 Nice to meet you!"

    elif "how are you" in user_input:
        return "I'm fine, thanks! 😊 How are you?"

    elif "your name" in user_input:
        return "I'm CodeBot, a simple Python chatbot. 🤖"

    elif user_input == "help":
        return (
            "You can say:\n"
            "- hello\n"
            "- how are you\n"
            "- what is your name\n"
            "- help\n"
            "- bye"
        )

    elif user_input in ["bye", "goodbye", "exit", "quit"]:
        return "Goodbye! 👋 Have a great day!"

    else:
        return "Sorry, I don't understand that yet. Try typing 'help'."


def main():

    print("=" * 45)
    print("           🤖 CODEBOT CHATBOT")
    print("=" * 45)

    print("Hello! I'm CodeBot.")
    print("Type 'help' to see what I can do.")
    print("Type 'bye' to exit.\n")

    while True:

        user_input = input("You: ")

        response = chatbot_response(user_input)

        print("Bot:", response)

        if user_input.lower().strip() in [
            "bye",
            "goodbye",
            "exit",
            "quit"
        ]:
            break


if __name__ == "__main__":
    main()